### PR TITLE
Allow user to set annotations and loadBalancerIP property of service

### PR DESCRIPTION
**Pull request by joephayes**
No issue for this change.

In order to set a DNS label on the load balancer in the azure environment I need to be able to set service annotations
To support a public IP address for the load balancer in the Azure environment I need to be able to set the loadBalancerIP property.

### CODE REVIEW

**Comment by joephayes** [comment]
Example stanza for values file:

```
service:
  annotations:
    # sets dns label for the load balancer. Azure will then automatically append a default subnet,
    # such as <location>.cloudapp.azure.com (where location is the region you selected), to the
    # name you provide, to create the fully qualified DNS name.
    service.beta.kubernetes.io/azure-dns-label-name: mydnslabel
  loadBalancerIP: xxx.xxx.xxx.xxx
```

**Review by pdmars — CHANGES_REQUESTED** [review]
Looks good to me. Can you create an issue for the release notes? It can be as simple as the PR title, just so I can track what was updated. Thanks!

**Comment by joephayes** [comment]
Resolves https://github.com/stardog-union/helm-charts/issues/46

**Comment by joephayes** [comment]
> Looks good to me. Can you create an issue for the release notes? It can be as simple as the PR title, just so I can track what was updated. Thanks!

Done!

**Pull request merged**
