### PR TITLE
PLAT-6142 - store admin PW in container environment, not on filesystem

### PR DESCRIPTION
**Pull request by gregoryg**
In response to 
https://stardog.atlassian.net/browse/PLAT-6142 - Security: Potential admin password leak

Bosch and other customers were concerned that the admin password was stored on the containers' file sytem.

This PR removes all file system writing / mounting of the password and stores it in an environment variable instead.

### CODE REVIEW

**Review by pdmars — APPROVED** [review]
Looks good to me. Wouldn't hurt to get @scardena or @ctffarley to weigh in before merging.

**Comment by lafirey** [comment]
@pdmars @scardena @ctffarley Where does this PR stand? Bosch is asking for this functionality so if it's a quick win to merge that's great. 

cc @mhgrove

**Comment by pdmars** [comment]
> @pdmars @scardena @ctffarley Where does this PR stand? Bosch is asking for this functionality so if it's a quick win to merge that's great.
> 
> cc @mhgrove

Looks like there's now a conflict to resolve, but otherwise I'm fine with it. Still would be good to get the cloud team to sign off, for awareness if nothing else.

**Review by scardena — COMMENTED** [review]
yep, looks good. just make sure you rebase the changes on latest, as @pdmars pointed out, seems there are some conflicts. after that, it should be good to go.

**Comment by pdmars** [comment]
This PR is from a fork. I'm going to close the PR, cherry pick this commit, resolve the conflict and open a new PR.

**Pull request closed without merging**
